minio:
  url: http://127.0.0.1:9000
  access-key: root
  secret-key: 12345678
  bucket-name: images

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: rainyrealestate@163.com
    password: HMHKTILCYXILDEMO
    protocol: smtp
