server:
  port: 8080
spring:
  application:
    name: service-user
  cache:
    type: caffeine
  profiles:
    active: base
    include: base,house,user
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: rainyrealestate@163.com
    password: HMHKTILCYXILDEMO
    protocol: smtp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/real_estate?serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 1
      max-active: 10
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      # 逻辑已删除值(默认为1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为0)
      logic-not-delete-value: 0
      table-prefix: tb_
  mapper-locations: classpath:mappers/*.xml

